export const SET_PLACES = 'SET_PLACES';
export const DELETE_PLACE = 'DELETE_PLACE';


export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const UI_SHOW_SHARE_PLACES = 'UI_SHOW_SHARE_PLACES';
export const UI_SHOW_FIND_PLACES = 'UI_SHOW_FIND_PLACES';
